name: PR Policy Check

on:
  pull_request:
    types: [opened, reopened, edited, synchronize, ready_for_review]

jobs:
  pr-policy:
    uses: hyperflowfinance/.github/.github/workflows/policy.yml@main
    secrets:
      JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
      JIRA_USER: ${{ secrets.JIRA_USER }}
      JIRA_TOKEN: ${{ secrets.JIRA_TOKEN }}
